// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.softrism.sencha.backend.domain;

import com.softrism.sencha.backend.domain.AppUser;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AppUser_Roo_Configurable {
    
    declare @type: AppUser: @Configurable;
    
}
